server:
    port: 9292

spring:
    application:
        name: CONFIG-SERVICE
    profiles:
        active: git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/dvazquez1027/configuration.git
                    clone-on-start: true
                    search-paths:
                    - "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost