server:
    port: 9292

spring:
    application:
        name: CONFIG-SERVICE
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/dvazquez1027/configuration.git
                    clone-on-start: true