server:
    port: 9292

spring:
    application:
        name: config-service
    profiles:
        active: git
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/dvazquez1027/microservices-demo-configuration.git
                    cloneOnStart: true
                    searchPaths: '{application}'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost